extractors:
  depth: depthanythingv2-outdoor
  normals: metric3dv2-normals # extractor normals from metric3dv2 wihtout caching it's depth estimates
reconstruction:
  image:
    depth:
      depth_uncertainty: 0.079
      prior_uncertainty: false
 