dataset:
    return_types:
      - "image"
      - "intrinsics"
model:
    name: dsine
    write_name: dsine-kappa
    config_file_name: dsine.txt
    config_dir_name: exp002_kappa
    return_types: 
      - "normals"
      - "normals2" 
      - "normals_variance"
      - "normals2_variance"
    scale: 1